_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
"N":
    value: 1024
T:
    value: 2
batch_size:
    value: 10
dt:
    value: 0.01
epochs:
    value: 5
learning_rate:
    value: 0.01
num_samples:
    value: 100
omega_range:
    value:
        - 0.5
        - 2
